print("Drawing a shape")
print ("This is a simple program to draw a shape using Python.")
print("Let's draw a square!")
print("     /|")
print("    / |")
print("   /  |")
print("  /   |")
print(" /    |")
print("/_____|")